# docker-compose
version: '3.7'

services:
  app:
    build: .
    command: echo 'ready'
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
